apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pdns.fullname" . }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pdns.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pdns.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.isClusterService }}
      dnsPolicy: Default
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint.sh"]
          args: ["--api={{ .Values.pdns.api.enabled }}", "--api-key={{ .Values.pdns.api.key }}", "--webserver=yes", "--webserver-port=8081", "--webserver-address=0.0.0.0", "--webserver-allow-from={{ .Values.pdns.webserver.allowFrom }}", "--slave=yes", "--dnsupdate={{ .Values.pdns.dnsupdate.enabled }}"]
          env:
              - name: MYSQL_HOST
                value: {{ template "mariadb.fullname" . }}
              - name: MYSQL_USER
                value: "root"
                value: {{ .Values.mariadb.mariadbUser | quote }}
              - name: MYSQL_PASS
                value: {{ .Values.mariadb.mariadbPassword | quote }}
              - name: MYSQL_DB
                value: {{ .Values.mariadb.mariadbDatabase | quote }}
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: api
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
